export const USER_SIGNIN_API = "SIGIN_API";
export const USER_SIGNUP_API = "SIGNUP_API";
export const GET_USER_BY_PROJECT_SAGA = "GET_USER_BY_PROJECT_SAGA";
export const GET_USER_BY_PROJECT_REDUCER = "GET_USER_BY_PROJECT_REDUCER";
